version: '3.8'
services:
  postgres-db:
    image: postgres:14-alpine
    container_name: hsl-bot-db
    restart: always
    environment:
      - POSTGRES_USER=botuser
      - POSTGRES_PASSWORD=botpassword
      - POSTGRES_DB=botdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: